---
- hosts: all
  remote_user: root
  pre_tasks:
    - name: Install openshift_facts requirements
      yum:
        name: "{{ item }}"
      with_items:
        - python-yaml
        - python-ipaddress
    - name: Include openshift_facts module
      import_role:
        name: "{{ openshift_ansible_dir }}/roles/openshift_facts"
    - name: Load openshift facts
      openshift_facts:
        role: common
  roles:
    - "{{ playbook_dir }}/openshift/roles/prerequisites"
    - "openshift-contrib/roles/docker-storage-setup"
  post_tasks:
    - name: Enable and start docker service
      service:
        state: started
        enabled: yes
        name: docker

- import_playbook: "{{ openshift_ansible_dir }}/playbooks/byo/config.yml"

- hosts: masters
  tasks:
    - name: Configure oc admin user for testing
      shell: |
        user_name="{{ admin_test_user_name | default('test_admin') }}"
        oc login -u system:admin
        oc get user "$user_name" || oc create user "$user_name"
        oc adm policy add-cluster-role-to-user cluster-admin "$user_name"
