---
# PARAMETERS
# - kubevirt_mf
# - kconfig
# - openshift_ansible_dir
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    lib_oc_path: "{{ openshift_ansible_dir }}/roles/lib_openshift"
  pre_tasks:
    - fail:
        msg: "Missing 'openshift_ansible_dir' parameter"
      when: openshift_ansible_dir is not defined
    - fail:
        msg: "Missing 'kconfig' parameter"
      when: kconfig is not defined
    - fail:
        msg: "Missing 'kubevirt_mf' parameter"
      when: kubevirt_mf is not defined
  roles:
    - "{{ playbook_dir }}/openshift/roles/kubevirt"
