- name: Download KubeVirt Template
  get_url:
    url: "{{ kubevirt_manifest_url }}/dev/{{ item }}.yaml.in"
    dest: "{{ playbook_dir }}/{{ kubevirt_template_dir }}/{{ item }}.yaml"
  with_items:
    - "{{ dev_template_resources }}"

- name: Rendering KubeVirt Yaml
  template:
    src: "{{ playbook_dir }}/{{ kubevirt_template_dir }}/{{ item }}.yaml"
    dest: "/tmp/{{ item }}.yaml"
  with_items:
    - "{{ dev_template_resources }}"

- file:
    path: "{{ playbook_dir }}/{{ kubevirt_template_dir }}/{{ item }}.yaml"
    state: absent
  with_items:
    - "{{ dev_template_resources }}"
  when: byo_template.stat.exists == False


- name: Create KubeVirt Resources
  command: "kubectl apply -f /tmp/{{ item }}.yaml"
  with_items:
    - "{{ dev_template_resources }}"
