- name: Download Kubevirt Template
  get_url:
    url: "{{ kubevirt_manifest_url }}/dev/{{ item }}"
    dest: "{{ kubevirt_template_dir }}/{{ item }}.yaml"
  with_items:
    - rbac.authorization.k8s
    - replicase-resource
    - virt-controller
    - virt-handler
    - vm-resource

- name: Rendering Kubevirt Yaml
  template:
    src: "{{ kubevirt_template_dir }}/{{ item }}.yaml"
    dest: /tmp/kubevirt.yaml
  with_items:
    - rbac.authorization.k8s
    - replicase-resource
    - virt-controller
    - virt-handler
    - vm-resource

- name: Create Kubevirt Resources
  command: kubectl apply -f /tmp/{{ item }}.yaml
  with_items:
    - rbac.authorization.k8s
    - replicase-resource
    - virt-controller
    - virt-handler
    - vm-resource
