- name: Login As Super User
  command: "oc login -u {{ admin_user }} -p {{ admin_password }}"
  when: cluster=="openshift"
        and admin_user is defined
        and admin_password is defined

- name: Create {{ namespace }} namespace
  shell: kubectl create namespace {{ namespace }}
  ignore_errors : true

- name: Add Privileged Policy
  command: "oc adm policy add-scc-to-user privileged -z {{ item }} -n {{ namespace }}"
  with_items:
    - kubevirt-privileged
    - kubevirt-controller
    - kubevirt-infra  # For KubeVirt v0.2.0
  when: cluster=="openshift"

- name: Add Hostmount-anyuid Policy
  command: "oc adm policy add-scc-to-user hostmount-anyuid -z kubevirt-infra -n {{ namespace }}"
  when: cluster=="openshift"

- name: Cheking for kubevirt.yaml template in {{ kubevirt_template_dir }}
  stat:
    path: "{{ kubevirt_template_dir }}/kubevirt.yaml"
  register: byo_template

- fail:
     msg: "Missing kubevirt.yaml in {{ kubevirt_template_dir }}"
     when: byo_template.stat.exists == False

- name: Using kubevirt.yaml template from {{ kubevirt_template_dir }}
  set_fact:
      template_version: "release"
  when: byo_template.stat.exists == True

- include_tasks: "{{ template_version }}.yaml"
