- name: Download Kubevirt Template
  get_url:
    url: "https://raw.githubusercontent.com/kubevirt/kubevirt/master/manifests/release/kubevirt.yaml.in"
    dest: "{{ kubevirt_template_dir }}/kubevirt.yaml"
  when: byo_template.stat.exists == False

- name: Rendering Kubevirt Yaml
  template:
    src: "{{ kubevirt_template_dir }}/kubevirt.yaml"
    dest: /tmp/kubevirt.yaml

- name: Create Kubevirt Resources
  command: kubectl apply -f /tmp/kubevirt.yaml
