epel_release_rpm_url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
openshift_ansible_dir: "openshift-ansible/"
openshift_playbook_path: "playbooks/byo/config.yml"
openshift_version: "3.7"
