---
- hosts: masters[0]
  roles:
    - role: generate-tests

- hosts: localhost
  connection: local
  gather_facts: False
  # unset http_proxy. required for running in the CI
  environment:
      http_proxy: ""
  vars:
    master_fqdn: "{{ hostvars[groups['masters'][0]]['ansible_fqdn'] }}"
    kubeconfig: "{{ playbook_dir }}/../admin.kubeconfig"
  tasks:
    - name: change kubeconfig to support insecure connection
      shell: |
        export KUBECONFIG="{{ kubeconfig }}"
        oc config set-cluster "{{ master_fqdn }}":8443 --insecure-skip-tls-verify=true
