- hosts: localhost
  connection: local
  gather_facts: False
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  vars:
    cluster: "openshift"
    action: "provision"
  roles:
    - role: kubevirt-resources
