- hosts: localhost
  connection: local
  gather_facts: False
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  vars:
    admin_test_user_name: "test_admin"
    admin_test_password: "123456"
    master_fqdn: "{{ hostvars[groups['masters'][0]]['ansible_fqdn'] }}"
  roles:
    - role: login-to-lago
